<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class XullTripSeeder extends Seeder
{
    /**
     * 20 trip realistis antar lokasi di Jabodetabek.
     * Origin & destination menggunakan koordinat akurat.
     * Trip diassign ke user dengan id 2–10 (non-admin).
     * Data final untuk presentasi NuraLoka.
     */
    public function run(): void
    {
        // Ambil id user non-admin (asumsikan admin = id 1)
        $userIds = DB::table('users')
            ->where('is_admin', false)
            ->orderBy('id')
            ->pluck('id')
            ->toArray();

        $trips = [
            [
                'user_idx' => 0,
                'title' => 'Eksplorasi Kota Tua dan Monas',
                'slug' => 'eksplorasi-kota-tua-dan-monas',
                'origin_name' => 'Stasiun Jakarta Kota',
                'origin_latitude' => -6.13740500,
                'origin_longitude' => 106.81335700,
                'destination_name' => 'Monumen Nasional (Monas)',
                'destination_latitude' => -6.17536700,
                'destination_longitude' => 106.82716400,
                'trip_date' => '2026-05-10',
                'is_public' => true,
            ],
            [
                'user_idx' => 1,
                'title' => 'Wisata Alam Kebun Raya Bogor',
                'slug' => 'wisata-alam-kebun-raya-bogor',
                'origin_name' => 'Terminal Kampung Rambutan Jakarta',
                'origin_latitude' => -6.32516700,
                'origin_longitude' => 106.87638900,
                'destination_name' => 'Kebun Raya Bogor',
                'destination_latitude' => -6.59883300,
                'destination_longitude' => 106.79854000,
                'trip_date' => '2026-05-17',
                'is_public' => true,
            ],
            [
                'user_idx' => 2,
                'title' => 'Road Trip ke Taman Safari',
                'slug' => 'road-trip-taman-safari-puncak',
                'origin_name' => 'Bekasi Timur',
                'origin_latitude' => -6.26972200,
                'origin_longitude' => 107.01666700,
                'destination_name' => 'Taman Safari Indonesia Cisarua',
                'destination_latitude' => -6.70416700,
                'destination_longitude' => 106.94722200,
                'trip_date' => '2026-05-24',
                'is_public' => true,
            ],
            [
                'user_idx' => 3,
                'title' => 'Belanja ke Tanah Abang',
                'slug' => 'belanja-ke-tanah-abang',
                'origin_name' => 'BSD City, Tangerang Selatan',
                'origin_latitude' => -6.30083300,
                'origin_longitude' => 106.65500000,
                'destination_name' => 'Pasar Tanah Abang',
                'destination_latitude' => -6.18750000,
                'destination_longitude' => 106.81333300,
                'trip_date' => '2026-06-01',
                'is_public' => false,
            ],
            [
                'user_idx' => 4,
                'title' => 'Liburan ke Kepulauan Seribu',
                'slug' => 'liburan-kepulauan-seribu',
                'origin_name' => 'Pelabuhan Muara Angke Jakarta',
                'origin_latitude' => -6.10555600,
                'origin_longitude' => 106.75583300,
                'destination_name' => 'Kepulauan Seribu',
                'destination_latitude' => -5.70930500,
                'destination_longitude' => 106.55215700,
                'trip_date' => '2026-06-07',
                'is_public' => true,
            ],
            [
                'user_idx' => 5,
                'title' => 'Jelajah Budaya Setu Babakan',
                'slug' => 'jelajah-budaya-setu-babakan',
                'origin_name' => 'Stasiun Depok Baru',
                'origin_latitude' => -6.38944400,
                'origin_longitude' => 106.81861100,
                'destination_name' => 'Setu Babakan Kampung Betawi',
                'destination_latitude' => -6.34361100,
                'destination_longitude' => 106.82027800,
                'trip_date' => '2026-06-14',
                'is_public' => true,
            ],
            [
                'user_idx' => 6,
                'title' => 'Kuliner Malam di Ancol',
                'slug' => 'kuliner-malam-ancol',
                'origin_name' => 'Kelapa Gading, Jakarta Utara',
                'origin_latitude' => -6.15888900,
                'origin_longitude' => 106.90305600,
                'destination_name' => 'Ancol Dreamland',
                'destination_latitude' => -6.12396500,
                'destination_longitude' => 106.83514400,
                'trip_date' => '2026-06-20',
                'is_public' => true,
            ],
            [
                'user_idx' => 7,
                'title' => 'Hiking Curug Nangka Bogor',
                'slug' => 'hiking-curug-nangka-bogor',
                'origin_name' => 'Stasiun Bogor',
                'origin_latitude' => -6.59555600,
                'origin_longitude' => 106.79194400,
                'destination_name' => 'Curug Nangka Bogor',
                'destination_latitude' => -6.68388900,
                'destination_longitude' => 106.72333300,
                'trip_date' => '2026-06-28',
                'is_public' => true,
            ],
            [
                'user_idx' => 8,
                'title' => 'Ziarah ke Masjid Istiqlal',
                'slug' => 'ziarah-masjid-istiqlal',
                'origin_name' => 'Tangerang Kota',
                'origin_latitude' => -6.17611100,
                'origin_longitude' => 106.63055600,
                'destination_name' => 'Masjid Istiqlal Jakarta',
                'destination_latitude' => -6.17008500,
                'destination_longitude' => 106.83085100,
                'trip_date' => '2026-07-05',
                'is_public' => false,
            ],
            [
                'user_idx' => 0,
                'title' => 'Weekend di TMII',
                'slug' => 'weekend-di-tmii',
                'origin_name' => 'Pondok Gede, Bekasi',
                'origin_latitude' => -6.29000000,
                'origin_longitude' => 106.91500000,
                'destination_name' => 'Taman Mini Indonesia Indah',
                'destination_latitude' => -6.30229000,
                'destination_longitude' => 106.89504600,
                'trip_date' => '2026-07-12',
                'is_public' => true,
            ],
            [
                'user_idx' => 1,
                'title' => 'Kulineran Soto Betawi di Jakarta',
                'slug' => 'kulineran-soto-betawi-jakarta',
                'origin_name' => 'Depok, Jawa Barat',
                'origin_latitude' => -6.39527800,
                'origin_longitude' => 106.82194400,
                'destination_name' => 'Kawasan Kuliner Menteng',
                'destination_latitude' => -6.19643800,
                'destination_longitude' => 106.83431500,
                'trip_date' => '2026-07-19',
                'is_public' => true,
            ],
            [
                'user_idx' => 2,
                'title' => 'Kunjungan Museum Nasional',
                'slug' => 'kunjungan-museum-nasional',
                'origin_name' => 'Bekasi Barat',
                'origin_latitude' => -6.24416700,
                'origin_longitude' => 106.97222200,
                'destination_name' => 'Museum Nasional Indonesia',
                'destination_latitude' => -6.17649900,
                'destination_longitude' => 106.82253800,
                'trip_date' => '2026-07-26',
                'is_public' => true,
            ],
            [
                'user_idx' => 3,
                'title' => 'Camping di Gunung Bunder',
                'slug' => 'camping-gunung-bunder-bogor',
                'origin_name' => 'Pamulang, Tangerang Selatan',
                'origin_latitude' => -6.36111100,
                'origin_longitude' => 106.72111100,
                'destination_name' => 'Gunung Bunder Bogor',
                'destination_latitude' => -6.73277800,
                'destination_longitude' => 106.71777800,
                'trip_date' => '2026-08-02',
                'is_public' => false,
            ],
            [
                'user_idx' => 4,
                'title' => 'Foto-foto di Kota Tua',
                'slug' => 'foto-foto-kota-tua-jakarta',
                'origin_name' => 'Kelapa Dua, Depok',
                'origin_latitude' => -6.35555600,
                'origin_longitude' => 106.81694400,
                'destination_name' => 'Kota Tua Jakarta',
                'destination_latitude' => -6.13487200,
                'destination_longitude' => 106.81320100,
                'trip_date' => '2026-08-09',
                'is_public' => true,
            ],
            [
                'user_idx' => 5,
                'title' => 'Belanja di Grand Indonesia',
                'slug' => 'belanja-grand-indonesia',
                'origin_name' => 'Bintaro, Tangerang Selatan',
                'origin_latitude' => -6.28722200,
                'origin_longitude' => 106.72388900,
                'destination_name' => 'Grand Indonesia Shopping Mall',
                'destination_latitude' => -6.19508700,
                'destination_longitude' => 106.82117200,
                'trip_date' => '2026-08-16',
                'is_public' => true,
            ],
            [
                'user_idx' => 6,
                'title' => 'Wisata Air di Ancol',
                'slug' => 'wisata-air-ancol-gondola',
                'origin_name' => 'Tanjung Priok, Jakarta Utara',
                'origin_latitude' => -6.10833300,
                'origin_longitude' => 106.87055600,
                'destination_name' => 'Gondola Ancol',
                'destination_latitude' => -6.12333300,
                'destination_longitude' => 106.84222200,
                'trip_date' => '2026-08-23',
                'is_public' => true,
            ],
            [
                'user_idx' => 7,
                'title' => 'Explore Kubah Mas Depok',
                'slug' => 'explore-masjid-kubah-mas-depok',
                'origin_name' => 'Sawangan, Depok',
                'origin_latitude' => -6.44500000,
                'origin_longitude' => 106.76388900,
                'destination_name' => 'Masjid Kubah Mas Depok',
                'destination_latitude' => -6.38999900,
                'destination_longitude' => 106.81330900,
                'trip_date' => '2026-09-06',
                'is_public' => false,
            ],
            [
                'user_idx' => 8,
                'title' => 'Curug Cilember Seru Bareng Keluarga',
                'slug' => 'curug-cilember-keluarga',
                'origin_name' => 'Cibinong, Bogor',
                'origin_latitude' => -6.47388900,
                'origin_longitude' => 106.85305600,
                'destination_name' => 'Curug Cilember Cisarua',
                'destination_latitude' => -6.66011100,
                'destination_longitude' => 106.95777800,
                'trip_date' => '2026-09-13',
                'is_public' => true,
            ],
            [
                'user_idx' => 0,
                'title' => 'Makan Siang di Ciawi Bogor',
                'slug' => 'makan-siang-sunda-ciawi-bogor',
                'origin_name' => 'Citeureup, Bogor',
                'origin_latitude' => -6.52111100,
                'origin_longitude' => 106.87277800,
                'destination_name' => 'Rumah Makan Sunda Cibiuk Ciawi',
                'destination_latitude' => -6.56666700,
                'destination_longitude' => 106.77500000,
                'trip_date' => '2026-09-20',
                'is_public' => true,
            ],
            [
                'user_idx' => 1,
                'title' => 'Waterboom Cikarang Bareng Teman',
                'slug' => 'waterboom-cikarang-bareng-teman',
                'origin_name' => 'Cibitung, Bekasi',
                'origin_latitude' => -6.29805600,
                'origin_longitude' => 107.09111100,
                'destination_name' => 'Waterboom Lippo Cikarang',
                'destination_latitude' => -6.35083300,
                'destination_longitude' => 107.14777800,
                'trip_date' => '2026-09-27',
                'is_public' => true,
            ],
        ];

        foreach ($trips as $trip) {
            $userIdx = $trip['user_idx'];
            unset($trip['user_idx']);

            $userId = $userIds[$userIdx] ?? $userIds[0];

            DB::table('trips')->insert([
                'user_id' => $userId,
                'title' => $trip['title'],
                'slug' => $trip['slug'],
                'origin_name' => $trip['origin_name'],
                'origin_latitude' => $trip['origin_latitude'],
                'origin_longitude' => $trip['origin_longitude'],
                'destination_name' => $trip['destination_name'],
                'destination_latitude' => $trip['destination_latitude'],
                'destination_longitude' => $trip['destination_longitude'],
                'trip_date' => $trip['trip_date'],
                'is_public' => $trip['is_public'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
