#!/bin/sh

echo "🔍 Running lint (Pint)..."

composer run lint

if [ $? -ne 0 ]; then
  echo "❌ Lint failed! Your code is still dirty. Please run 'composer format' OR 'composer run format'."
  exit 1
fi

echo "✅ Lint passed!"
exit 0


